# Main configuration file for NoCheat. Read "Instructions.txt"
logging:
  active: true
  showactivechecks: false
  debugmessages: false
  prefix: '&4NC&f: '
  filename: nocheat.log
  file: true
  console: true
  ingamechat: true
checks:
  inventory:
    drop:
      active: true
      time: 20
      limit: 100
      actions: log:drop:0:1:cif cmd:kick
    instantbow:
      active: true
      actions: log:ibow:2:5:if cancel
    instanteat:
      active: true
      actions: log:ieat:2:5:if cancel
  moving:
    runfly:
      active: true
      allowfastsneaking: false
      actions: log:moveshort:3:5:f cancel vl>100 log:moveshort:0:5:if cancel vl>400 log:movelong:0:5:cif cancel
      checknofall: true
      nofallaggressivemode: true
      nofallactions: log:nofall:0:5:cif cancel
      flying:
        allowflyingalways: false
        allowflyingincreative: true
        flyingspeedlimithorizontal: 60
        flyingspeedlimitvertical: 100
        flyingheightlimit: 128
        actions: log:moveshort:3:5:f cancel vl>100 log:moveshort:0:5:if cancel vl>400 log:movelong:0:5:cif cancel
    morepackets:
      active: true
      actions: log:morepackets:3:2:if cancel vl>20 log:morepackets:0:2:if cancel
  blockbreak:
    reach:
      active: true
      actions: cancel vl>5 log:bbreach:0:2:if cancel
    direction:
      active: true
      precision: 50
      penaltytime: 300
      actions: cancel vl>10 log:bbdirection:0:5:if cancel
    noswing:
      active: true
      actions: log:bbnoswing:3:2:if cancel
  blockplace:
    reach:
      active: true
      actions: cancel vl>5 log:bpreach:0:2:if cancel
    direction:
      active: true
      precision: 75
      penaltytime: 100
      actions: cancel vl>10 log:bpdirection:0:3:if cancel
  chat:
    color:
      active: true
      actions: log:color:0:1:if cancel
    spam:
      active: true
      whitelist: ''
      timeframe: 3
      messagelimit: 3
      commandlimit: 12
      actions: log:spam:0:3:if cancel vl>30 log:spam:0:3:cif cancel cmd:kick
  fight:
    direction:
      active: true
      precision: 75
      penaltytime: 500
      actions: cancel vl>5 log:fdirection:3:5:f cancel vl>20 log:fdirection:0:5:if cancel vl>50 log:fdirection:0:5:cif cancel
    noswing:
      active: true
      actions: log:fnoswing:0:5:cif cancel
    reach:
      active: true
      distance: 400
      penaltytime: 500
      actions: cancel vl>10 log:freach:2:5:if cancel
    speed:
      active: true
      attacklimit: 15
      actions: log:fspeed:0:5:if cancel
    godmode:
      active: true
      actions: log:fgod:2:5:if cancel
    instantheal:
      active: true
      actions: log:fheal:1:1:if cancel
strings:
  drop: '[player] failed [check]: Tried to drop more items than allowed. VL [violations]'
  moveshort: '[player] failed [check]. VL [violations]'
  movelong: '[player] in [world] at [location] moving to [locationto] over distance [movedistance] failed check [check]. Total violation level so far [violations]'
  nofall: '[player] failed [check]: tried to avoid fall damage for ~[falldistance] blocks. VL [violations]'
  morepackets: '[player] failed [check]: Sent [packets] more packets than expected. Total violation level [violations]'
  bbreach: '[player] failed [check]: tried to interact with a block over distance [reachdistance]. VL [violations]'
  bbdirection: '[player] failed [check]: tried to interact with a block out of line of sight. VL [violations]'
  bbnoswing: '[player] failed [check]: Didn''t swing arm. VL [violations]'
  bpreach: '[player] failed [check]: tried to interact with a block over distance [reachdistance]. VL [violations]'
  bpdirection: '[player] failed [check]: tried to interact with a block out of line of sight. VL [violations]'
  color: '[player] failed [check]: Sent colored chat message ''[text]''. VL [violations]'
  spam: '[player] failed [check]: Last sent message ''[text]''. VL [violations]'
  fdirection: '[player] failed [check]: tried to interact with a block out of line of sight. VL [violations]'
  freach: '[player] failed [check]: tried to attack entity out of reach. VL [violations]'
  fspeed: '[player] failed [check]: tried to attack more than [limit] times per second. VL [violations]'
  fnoswing: '[player] failed [check]: Didn''t swing arm. VL [violations]'
  fgod: '[player] failed [check]: Avoided taking damage or lagging. VL [violations]'
  fheal: '[player] failed [check]: Tried to regenerate health faster than normal. VL [violations]'
  ibow: '[player] failed [check]: Fires bow to fast. VL [violations]'
  ieat: '[player] failed [check]: Eats food [food] too fast. VL [violations]'
  kick: kick [player]
